language: python
install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]] ; then brew install python virtualenv pip; fi
    - pip install --user -r requirements.txt
python:
    - 2.7
    - 3.2
    - 3.3
    - 3.4
    - 3.5
os:
    - linux
    - osx
sudo: false
script: nosetests
